services:
  postgres:
    container_name: pg_db
    image: postgres
    environment:
      POSTGRES_USER: yujin
      POSTGRES_PASSWORD: yujin
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pg_dashboard
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: sayeed205@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 9015@Pgadmin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - '5050:80'
    networks:
      - postgres
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

  typesense:
    container_name: typesense
    image: typesense/typesense:26.0
    restart: on-failure
    ports:
      - '8108:8108'
    volumes:
      - typesense:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'

  resque-web:
    image: appwrite/resque-web
    container_name: resque-web
    ports:
      - '5678:5678'
    environment:
      - RESQUE_WEB_HOST=redis # (OPTIONAL - Use only if different than the default 127.0.0.1)
      - RESQUE_WEB_PORT=6379 # (OPTIONAL - Use only if different the default 6379)
      - RESQUE_WEB_HTTP_BASIC_AUTH_USER= # (OPTIONAL - if not set no password used)
      - RESQUE_WEB_HTTP_BASIC_AUTH_PASSWORD= # (OPTIONAL - if not set no password used)
    depends_on:
      - redis
    restart: unless-stopped
networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  redis:
  typesense:
