services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: yujin
      POSTGRES_PASSWORD: yujin
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pg
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: sayeed205@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 9015@Pgadmin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - '5050:80'
    networks:
      - postgres
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

  typesense:
    container_name: typesense
    image: typesense/typesense:26.0
    restart: on-failure
    ports:
      - '8108:8108'
    volumes:
      - typesense:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  redis:
  typesense:
